name: Build Extension

on: pull_request

jobs:
  build_extension:
    name: Build Extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.22.0
      - name: Build Extension
        run: |
          yarn install
          yarn build
